# Generated by Django 5.0.4 on 2024-05-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('0', 'sugerencia'), ('1', 'consulta'), ('2', 'oferta laboral'), ('3', 'oferta práctica')], max_length=20)),
                ('asunto', models.CharField(max_length=50)),
                ('texto', models.TextField()),
            ],
        ),
    ]
