# Generated by Django 5.0.4 on 2024-06-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('imagen_url', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=50)),
            ],
        ),
    ]
